version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/microparts/configuration-golang

    environment: # environment variables for the build itself
      IN_CONTAINER: true
      DEP_VERSION: 0.5.0

    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /bin/dep && chmod +x /bin/dep
      - run: make all
      - run: make tests