version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    parallelism: 4
    environment: # environment variables for the build itself
      - IN_CONTAINER: true
      - GO111MODULE: "on"

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/microparts/configuration-golang

    steps:
      - checkout
      - run: go mod vendor
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: tests
          command: |
            sudo mkdir -p /cfgs/defaults
            sudo mkdir -p /cfgs/development
            sudo chown -R circleci:circleci /cfgs
            ln -s ${CIRCLE_WORKING_DIRECTORY}/test/configuration/defaults/* /cfgs/defaults/
            ln -s ${CIRCLE_WORKING_DIRECTORY}/test/configuration/development/* /cfgs/development/
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
            mv c.out /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/*
